name: The Block Box
favicon: null
layout_spectrum: 0.4653
typography_spectrum: 0.64835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9d7938'
    - '#060683'
    - '#ffffff'
    - '#ffff00'
    - '#008080'
  brandStrength: 0.6353707413654774
  lightness: 0.5893200011923909
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
